### ISSUE TITLE
Async calls does not work from sync call?

### ISSUE THREAD

**Issue by PatriceDargenton** [JnRMnT/JMovies.IMDb#12]
I think asynchronous calls are not working from synchronous calls in your project. Only tests work fine, but they are asynchronous. Can you verify that synchronous calls can work with your latest asynchronous code?
Thanks.

With the latest version, my code gets stuck in GetMovie() indefinitely.
I had to create a branch from your last synchronous release: Classic_sync_version:
https://github.com/PatriceDargenton/JMovies.IMDb/commit/73fa884f55edd71c473479bd46055b6186636cbe

Also there is a strange issue: Some tests are not detected by Visual Studio 2022: SpecificMoviesTests???

**Comment by JnRMnT** [comment]
Hi @PatriceDargenton

I have seen that due to design change on some pages of IMDB, many methods and tests are failing. I am in the process of fixing them. After that I will have a look to this as well.

**Comment by PatriceDargenton** [comment]
Hi @JnRMnT, I tried the new version, the tests are good now, but there is still this problem with the synchronous call of the async function, it seems that it does not work, I have an infinite loop in GetMovie with return GetMovieAsync(id).Result;
(GetMovie works fine from tests, but not from synchronous calls it seems)

And there are also tests that are not detected as test: internal class SpecificMoviesTests : public class ! Not internal !

**Comment by JnRMnT** [comment]
I have updated the test class and created an example console app project. It seems to be working. Can you debug your project and let me know where it is stuck in infinite loop exactly? It might be also related to some of your project dependencies, it would help if you can share some parts of the project.

**Comment by PatriceDargenton** [comment]
Your ExampleApp is working fine, thanks! I have a ClassLib in .Net6 exactly the same as your ExampleApp, except yours is a console app, instead of a ClassLib, but I still have the same bug, maybe it's a OleDbConnection issue or a WindowsForm issue (I have to search from a database), I'll keep looking for a solution, thanks for your great help!

**Comment by PatriceDargenton** [comment]
Hi @JnRMnT, I tried a WinForm App and a WPF App in C#, and in both the async version does not work, while the Console App works fine. So it is a desktop app issue (this is not a OleDbConnection issue).

**Comment by JnRMnT** [comment]
This is now fixed with v1.8.3, please check again.
