### ISSUE TITLE
Null reference issue

### ISSUE THREAD

**Issue by foxi69** [JnRMnT/JMovies.IMDb#14]
**Describe the bug**
Your test App is not working for me, null reference issue

```
            IIMDbDataProvider imdbDataProvider = new IMDbScraperDataProvider();
            JMovies.IMDb.Entities.Movies.Movie movie = await imdbDataProvider.GetMovieAsync(7456722, new BasicProductionDataFetchSettings {
                PreferredCulture = "en-US"
            });
```

![error](https://github.com/JnRMnT/JMovies.IMDb/assets/2604798/d44539db-8674-478d-bf28-aa2f4d9878aa)

**Comment by JnRMnT** [comment]
Hi @foxi69 , having a look now but please bear in mind that this library uses web scraping, so if any simple change in the UI of IMDB, this will start to fail. If that happens, I might not have the time to quickly fix it. I would appricate it if you can have a quick look if its a simple fix, maybe you can send a PR, if not it would be great if you could give some info on what is failing.
