### ISSUE TITLE
this not working

### ISSUE THREAD

**Issue by PouyaForozia** [JnRMnT/JMovies.IMDb#2]
Hi,
This line of code 
          //Parse and verify IMDb ID Meta Tag
            HtmlNode idMetaTag = documentNode.QuerySelector("meta[property='pageId']");
not working anymore always null

**Comment by JnRMnT** [comment]
Hi, sorry for checking this post late but indeed with the new design coming into public availability of IMDB; the movie parsing stopped working. I will take a look as soon as i can.

**Comment by JnRMnT** [comment]
commit #2457eb8f22589bd67ef2ec99edf425d242a2ef1c should fix this. Please try again and let me know of your feedback!
