### ISSUE TITLE
IMDbScraperDataProvider add "/" after scraper URL

### ISSUE THREAD

**Issue by nikisbeta** [JnRMnT/JMovies.IMDb#4]
Please add "/" after scraper URL, otherwise, the server returns error 308 (pernamently redirect)

![image](https://user-images.githubusercontent.com/8208104/148235630-51e4eff0-f0ba-4c29-98ef-34c9f68db770.png)

**Comment by nikisbeta** [comment]
Sorry,
should only be added correctly for the first request
![image](https://user-images.githubusercontent.com/8208104/148236591-843ca1c7-7f2f-4748-a7aa-bbcd1c91b973.png)

**Comment by JnRMnT** [comment]
Hi, thanks for reporting. I will check this as soon as i can.
