### ISSUE TITLE
Get all AKAs by Country

### ISSUE THREAD

**Issue by foxi69** [JnRMnT/JMovies.IMDb#5]
![pic](https://user-images.githubusercontent.com/2604798/168313991-e100f5c4-10c6-456e-ace0-df96ec9b1c64.png)

```
JMovies.IMDb.Providers.IMDbScraperDataProvider movie = new JMovies.IMDb.Providers.IMDbScraperDataProvider();
var movieData = movie.GetMovie(0038969);
foreach (var item in movieData.AKAs) {
    list.Add(item.Name);
}
```

https://www.imdb.com/title/tt0038969

Its only leave me one AKA.

Where can i change the ScrapingCulture?

**Comment by JnRMnT** [comment]
On the AKAs:
1- I had not implemented the logic of parsing AKAs from this page. I accepted this as an enhancement and created a new version of the package. You can check with the latest version now.
2- You should be using "FullProductionDataFetchSettings" if you want to get these details as they are not available on the main page of the movie.
3- Changing Scraping Culture was also not implemented. I added support for this and documented in the "How to use" section.

**Comment by foxi69** [comment]
Thanks!

It works!
My last question is the following:

Can i search imdbData by String (Movie/Series Title)?
